# Generated by Django 5.0 on 2024-05-21 10:06

import Base.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filenew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('sld_file', models.FileField(blank=True, null=True, upload_to='slds/')),
                ('data_from_sld', models.FileField(blank=True, null=True, upload_to='slds/')),
                ('excel_intermediate_file', models.FileField(blank=True, null=True, upload_to='excels/')),
                ('excel_output_file', models.FileField(blank=True, null=True, upload_to='excels/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationname', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MultiProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_products', models.FileField(upload_to='products/')),
                ('data_from_multi_products', models.FileField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_rating', models.IntegerField(blank=True, null=True)),
                ('fault_current', models.IntegerField(blank=True, null=True)),
                ('power_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phase', models.CharField(blank=True, choices=[('Three Phase', 'Three Phase'), ('Single Phase', 'Single Phase')], max_length=20, null=True)),
                ('poles', models.CharField(blank=True, choices=[('3 Pole', '3 Pole'), ('4 Pole', '4 Pole')], max_length=20, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on-progress', 'On Progress'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_number',
            field=models.CharField(max_length=15, validators=[Base.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='upload_loadschedule',
            field=models.FileField(help_text='Upload PDF file only', upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='upload_sld',
            field=models.ImageField(upload_to='sld/'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('contact', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxpercentage', models.CharField(max_length=255)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.location')),
            ],
        ),
    ]
