# Generated by Django 4.2.3 on 2024-08-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_searchrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchRecord',
        ),
    ]
